sonar.projectKey=ritu-chudasama_Weekmate-Staging
sonar.organization=ritu-chudasama
sonar.sources=wp-content/themes/weekmate
sonar.exclusions=**/node_modules/**,**/vendor/**,**/*.min.js,**/*.min.css
sonar.sourceEncoding=UTF-8
